import { checkbox, relationship, select, text } from '@keystone-next/fields';

import { list } from '@keystone-next/keystone/schema';
import { LakeImage } from './LakeImage';

export const Lake = list({
  fields: {
    name: text({ isRequired: true }),
    address: text({ isRequired: true }),
    address2: text({ isRequired: false }),
    city: text({ isRequired: true }),
    state: select({
      isRequired: true,
      options: [
        { value: 'AK', label: 'Alaska' },
        { value: 'TX', label: 'Texas' },
        { value: 'AL', label: 'Alabama' },
        { value: 'AR', label: 'Arkansas' },
        { value: 'AZ', label: 'Arizona' },
        { value: 'CA', label: 'California' },
        { value: 'CO', label: 'Colorado' },
        { value: 'CT', label: 'Connecticut' },
        { value: 'DC', label: 'DistrictofColumbia' },
        { value: 'DE', label: 'Delaware' },
        { value: 'FL', label: 'Florida' },
        { value: 'GA', label: 'Georgia' },
        { value: 'HI', label: 'Hawaii' },
        { value: 'IA', label: 'Iowa' },
        { value: 'ID', label: 'Idaho' },
        { value: 'IL', label: 'Illinois' },
        { value: 'IN', label: 'Indiana' },
        { value: 'KS', label: 'Kansas' },
        { value: 'KY', label: 'Kentucky' },
        { value: 'LA', label: 'Louisiana' },
        { value: 'MA', label: 'Massachusetts' },
        { value: 'MD', label: 'Maryland' },
        { value: 'ME', label: 'Maine' },
        { value: 'MI', label: 'Michigan' },
        { value: 'MN', label: 'Minnesota' },
        { value: 'MO', label: 'Missouri' },
        { value: 'MS', label: 'Mississippi' },
        { value: 'MT', label: 'Montana' },
        { value: 'NC', label: 'NorthCarolina' },
        { value: 'ND', label: 'NorthDakota' },
        { value: 'NE', label: 'Nebraska' },
        { value: 'NH', label: 'NewHampshire' },
        { value: 'NJ', label: 'NewJersey' },
        { value: 'NM', label: 'NewMexico' },
        { value: 'NV', label: 'Nevada' },
        { value: 'NY', label: 'NewYork' },
        { value: 'OH', label: 'Ohio' },
        { value: 'OK', label: 'Oklahoma' },
        { value: 'OR', label: 'Oregon' },
        { value: 'PA', label: 'Pennsylvania' },
        { value: 'RI', label: 'RhodeIsland' },
        { value: 'SC', label: 'SouthCarolina' },
        { value: 'SD', label: 'SouthDakota' },
        { value: 'TN', label: 'Tennessee' },
        { value: 'TX', label: 'Texas' },
        { value: 'UT', label: 'Utah' },
        { value: 'VA', label: 'Virginia' },
        { value: 'VT', label: 'Vermont' },
        { value: 'WA', label: 'Washington' },
        { value: 'WI', label: 'Wisconsin' },
        { value: 'WV', label: 'WestVirginia' },
        { value: 'WY', label: 'Wyoming' },
      ],
    }),
    zip: text({ isRequired: true }),
    description: text({
      ui: {
        displayMode: 'textarea',
      },
    }),
    photo: relationship({
      ref: 'LakeImage.lake',
      many: true,
      ui: {
        displayMode: 'cards',
        cardFields: ['image', 'altText'],
        inlineCreate: { fields: ['image', 'altText'] },
        inlineEdit: { fields: ['image', 'altText'] },
      },
    }),
    largemouth: checkbox({
      defaultValue: false,
      isRequired: true,
    }),
    smallmouth: checkbox({
      defaultValue: false,
      isRequired: true,
    }),
    spotted: checkbox({
      defaultValue: false,
      isRequired: true,
    }),
  },
});
