import { text, relationship, select, integer } from '@keystone-next/fields';
import { list } from '@keystone-next/keystone/schema';

export const Ramp = list({
  fields: {
    lake: relationship({ ref: 'Lake' }),
    name: text({ isRequired: true }),
    address: text({ isRequired: true }),
    address2: text({ isRequired: false }),
    city: text({ isRequired: true }),
    state: select({
      isRequired: true,
      options: [
        { value: 'AK', label: 'Alaska' },
        { value: 'TX', label: 'Texas' },
        { value: 'AL', label: 'Alabama' },
        { value: 'AR', label: 'Arkansas' },
        { value: 'AZ', label: 'Arizona' },
        { value: 'CA', label: 'California' },
        { value: 'CO', label: 'Colorado' },
        { value: 'CT', label: 'Connecticut' },
        { value: 'DC', label: 'DistrictofColumbia' },
        { value: 'DE', label: 'Delaware' },
        { value: 'FL', label: 'Florida' },
        { value: 'GA', label: 'Georgia' },
        { value: 'HI', label: 'Hawaii' },
        { value: 'IA', label: 'Iowa' },
        { value: 'ID', label: 'Idaho' },
        { value: 'IL', label: 'Illinois' },
        { value: 'IN', label: 'Indiana' },
        { value: 'KS', label: 'Kansas' },
        { value: 'KY', label: 'Kentucky' },
        { value: 'LA', label: 'Louisiana' },
        { value: 'MA', label: 'Massachusetts' },
        { value: 'MD', label: 'Maryland' },
        { value: 'ME', label: 'Maine' },
        { value: 'MI', label: 'Michigan' },
        { value: 'MN', label: 'Minnesota' },
        { value: 'MO', label: 'Missouri' },
        { value: 'MS', label: 'Mississippi' },
        { value: 'MT', label: 'Montana' },
        { value: 'NC', label: 'NorthCarolina' },
        { value: 'ND', label: 'NorthDakota' },
        { value: 'NE', label: 'Nebraska' },
        { value: 'NH', label: 'NewHampshire' },
        { value: 'NJ', label: 'NewJersey' },
        { value: 'NM', label: 'NewMexico' },
        { value: 'NV', label: 'Nevada' },
        { value: 'NY', label: 'NewYork' },
        { value: 'OH', label: 'Ohio' },
        { value: 'OK', label: 'Oklahoma' },
        { value: 'OR', label: 'Oregon' },
        { value: 'PA', label: 'Pennsylvania' },
        { value: 'RI', label: 'RhodeIsland' },
        { value: 'SC', label: 'SouthCarolina' },
        { value: 'SD', label: 'SouthDakota' },
        { value: 'TN', label: 'Tennessee' },
        { value: 'TX', label: 'Texas' },
        { value: 'UT', label: 'Utah' },
        { value: 'VA', label: 'Virginia' },
        { value: 'VT', label: 'Vermont' },
        { value: 'WA', label: 'Washington' },
        { value: 'WI', label: 'Wisconsin' },
        { value: 'WV', label: 'WestVirginia' },
        { value: 'WY', label: 'Wyoming' },
      ],
    }),
    zip: text({ isRequired: true }),
    costToLaunch: text({ isRequired: true }),

    bathrooms: select({
      isRequired: true,
      options: [
        { value: 'Yes', label: 'Yes' },
        { value: 'No', label: 'No' },
      ],
    }),
    numberOfRamps: integer({
      defaultValue: 0,
      isRequired: true,
    }),
    trailerParkingSpots: select({
      isRequired: false,
      options: [
        { value: 'Less than 10', label: 'Less than 10' },
        { value: '10-20', label: '10-20' },
        { value: '20-30', label: '20-30' },
        { value: '30-40', label: '30-40' },
        { value: '40-50', label: '40-50' },
        { value: '50-60', label: '50-60' },
        { value: '60-70', label: '60-70' },
        { value: '70-80', label: '70-80' },
        { value: '80-90', label: '80-90' },
        { value: '90-100', label: '90-100' },
        { value: '100 Plus', label: '100 Plus' },
        {
          value: 'Bassmaster Level Parking',
          label: 'Bassmaster Level Parking',
        },
      ],
    }),
    areTournamentsPremitted: select({
      isRequired: false,
      options: [
        { value: 'Yes', label: 'Yes' },
        { value: 'No', label: 'No' },
      ],
    }),
    isFourWheelDriveNeeded: select({
      isRequired: false,
      options: [
        { value: 'Yes', label: 'Yes' },
        { value: 'No', label: 'No' },
        { value: 'Only in the winter', label: 'Only in the winter' },
      ],
    }),
    extraRampDetails: text({
      ui: {
        displayMode: 'textarea',
      },
    }),

    photo: relationship({
      ref: 'RampImage.ramp',
      many: true,
      ui: {
        displayMode: 'cards',
        cardFields: ['image', 'altText'],
        inlineCreate: { fields: ['image', 'altText'] },
        inlineEdit: { fields: ['image', 'altText'] },
      },
    }),
  },
});
